### ISSUE TITLE
Suport for Python and Java?

### ISSUE THREAD

**Issue by pjodouin** [XT-i/aws-lambda-jenkins-plugin#22]
Hi, 

Great plugin for AWS Lambda but can you please add the two new runtimes that are now supported on Lambda: Python and Java?

Thanks!

**Comment by cast** [comment]
Hi Pjodouin,

I explicitely used string fields instead of select boxes to allow for rapid AWS Lambda changes without updating the plugin (barring documentation)

These options should be possible in the runtime text field: nodejs, java8, python2.7

Can you try the last one?

Thanks,

Michael Willemse

**Comment by pjodouin** [comment]
Hi Michael,

Yes, I realized later after posting the issue that there was no actual
validation on the field.  Originally I had tried "Python" and got an error
from the Lambda service, not the plugin--sorry. "Python2.7" works fine.

Very useful plugin!

Thanks,
Pierre

On Wed, Oct 14, 2015 at 12:51 PM, Michael Willemse <notifications@github.com
