### ISSUE TITLE
Support for temporary credentials

### ISSUE THREAD

**Issue by ranjansumit** [XT-i/aws-lambda-jenkins-plugin#61]
Currently we need to give 'AWS Access key ID' and 'AWS Secret Access Key' in the jenkins.
I want to use temporary credentials only. For that 
I could not find a way to enter 'AWS session Token' in the plugin. 
Please add support for that or let me know if there is some existing way to enter temporary credentials.

**Comment by cast** [comment]
Hi Ranjansumit,

You can tick the "Use instance credentials" check box to use the DefaultAWSCredentialsProviderChain with the following order:

Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or AWS_ACCESS_KEY and AWS_SECRET_KEY (only recognized by Java SDK)
Java System Properties - aws.accessKeyId and aws.secretKey
Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
Credentials delivered through the Amazon EC2 container service if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" environment variable is set and security manager has permission to access the variable,
Instance profile credentials delivered through the Amazon EC2 metadata service
